name: flutter_chat_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  firebase_storage: ^10.0.6
  cloud_firestore: ^2.5.4
  google_sign_in: ^5.2.1

  location: ^4.3.0
  google_maps_flutter: ^2.1.2

  flutter_native_splash: ^1.2.4
  lottie: ^1.2.1

  get: ^4.3.8
  get_storage: ^2.0.3
  provider: ^6.0.2

  avatar_glow: ^2.0.1
  image_picker: ^0.8.4+2
  video_player: ^2.2.5
  emoji_picker_flutter: ^1.0.7
  date_format: ^2.0.6

  encrypt: ^5.0.1


  cupertino_icons: ^1.0.2
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

